version: '3.7'

services:

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=texts
      - POSTGRES_PASSWORD=texts
      - POSTGRES_DB=texts

  redis:
    image: redis:5.0.6-alpine
    volumes:
      - redis_data:/data

  celery:
    build: ./app
    command: celery -A texts worker -l INFO
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - redis
      - postgres

  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - postgres
      - redis

volumes:

  postgres_data:
  redis_data:
