# Generated by Django 2.1 on 2018-08-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20180809_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('+', 'Plus'), ('-', 'Minus')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Text'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
