# Generated by Django 2.1 on 2018-08-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_text_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='direction',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(default=1),
        ),
    ]
