# Generated by Django 2.1.7 on 2019-02-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190223_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='image_url',
            new_name='file_name',
        ),
    ]
